In [1]:
import os
thisFilePath=os.path.abspath('.')
os.chdir(thisFilePath)
os.getcwd()


'C:\\Users\\Administrator\\Desktop\\python课程\\myFolder20181127'

In [2]:
import pandas as pd
mydata = pd.read_csv('DataForClassify.csv',encoding="gb2312",usecols = ['yuwen','lishi','zhengzhi','shuxue','wuli','huaxue','ClassifyResult'])

train_x=mydata.iloc[:,1:7].values
train_y=mydata.iloc[:,0].values

In [3]:
print("train_x:",train_x[:5],"train_y",train_y)

train_x: [[84 86 75 67 74 51]
 [79 79 70 77 81 81]
 [79 60 69 83 81 80]
 [77 71 79 90 72 80]
 [88 71 84 78 79 75]] train_y [1 2 3 2 2 2 1 3 3 3 2 2 2 1 2 2 3 1 2 2 2 1 2 2 2 3 1 2 2 1 2 1 2 2 1 3 1
 1 3 3 2 2 1 1 3 1 2 1 1 3 1 1 3 3 1 2 1 3 1 1 1 1 3 1 3 1 3 1 2 1 2 3 3 3
 3 1 3 2 2 1 1 3 1 1 2 2 1 2 1 1 1 3 1 2 3 3 2 2 1 2]


In [4]:
import numpy as np
train_x_std=pd.DataFrame(train_x).corr()
train_x_std


0         1         2         3         4         5
0  1.000000  0.697769  0.740321 -0.529724 -0.543280 -0.576379
1  0.697769  1.000000  0.635897 -0.550157 -0.571269 -0.591023
2  0.740321  0.635897  1.000000 -0.591599 -0.581079 -0.598415
3 -0.529724 -0.550157 -0.591599  1.000000  0.603851  0.680201
4 -0.543280 -0.571269 -0.581079  0.603851  1.000000  0.630192
5 -0.576379 -0.591023 -0.598415  0.680201  0.630192  1.000000

In [5]:
import numpy.linalg as nlg
eig_value,eig_vector=nlg.eig(R)
eig_value

NameError: name 'R' is not defined

In [8]:
eig=pd.DataFrame()
eig.sort_values('eig_value',ascending=False,inplace=True)
eig

KeyError: 'eig_value'

In [7]:
for m in range(1,len(eig)+1):
    print("第"+str(m)+"个主成分的累积贡献率是："+str(eig['eig_value'][:m].sum()/eig['eig_value'].sum()))

NameError: name 'eig' is not defined